#!/bin/sh
# Regenerates lib/piratetok.proto from the live-lua proto schemas (same tags as live-rs).
# usage: tools/gen_schema.sh [path/to/live-lua]
set -e
LUA_DIR=${1:-../live-lua}
OUT=$(dirname "$0")/../lib/piratetok.proto
{
    echo 'syntax = "proto3";'
    echo "// GENERATED by tools/gen_schema.sh from live-lua piratetok/proto/*.lua - do not edit"
    for f in common frames messages messages_ext; do
        awk '/\[\[/{on=1; next} /\]\]/{on=0} on && !/^syntax/' "$LUA_DIR/piratetok/proto/$f.lua"
    done
} > "$OUT"
echo "wrote $OUT"
